### ISSUE TITLE
Sample code doesn't build

### ISSUE THREAD

**Issue by KutanaDev** [dittodhole/dotnet-Contrib.System.Printing.Xps#1]
I was thrilled to see this NuGet package. I installed it, and then pasted the sample code from the front page into a new function in a VS2013 project, but when I built I got three errors:

> T:\Development\Sandbox\XpsNugetSample\Program.cs(24,38,24,43): error CS1061: 'Contrib.System.Printing.Xps.IXpsPrinterDefinition' does not contain a definition for 'Print' and no extension method 'Print' accepting a first argument of type 'Contrib.System.Printing.Xps.IXpsPrinterDefinition' could be found (are you missing a using directive or an assembly reference?)

> T:\Development\Sandbox\XpsNugetSample\Program.cs(35,42,35,47): error CS1061: 'Contrib.System.Printing.Xps.IXpsPrinterDefinition' does not contain a definition for 'Print' and no extension method 'Print' accepting a first argument of type 'Contrib.System.Printing.Xps.IXpsPrinterDefinition' could be found (are you missing a using directive or an assembly reference?)

> T:\Development\Sandbox\XpsNugetSample\Program.cs(38,92,38,106): error CS1061: 'Contrib.System.Printing.Xps.IXpsInputBinDefinition' does not contain a definition for 'GetPrintTicket' and no extension method 'GetPrintTicket' accepting a first argument of type 'Contrib.System.Printing.Xps.IXpsInputBinDefinition' could be found (are you missing a using directive or an assembly reference?)

How do I get these errors to go away? Is the sample code in sync with the latest NuGet release?

Best wishes
Brian THOMAS

**Comment by dittodhole** [comment]
Thanks for bringing this issue to my attention!

It seems that the example is missing a crucial `using` - fixed it 🍻

**Comment by dittodhole** [comment]
You have to provide an `System.Windows.Documents.IDocumentPaginatorSource` object yourself to make the example work.
I can't and won't provide you with an actual instance - I am just showing off the API.

This said, to make your example work, please provide the `Print`-method with your own `System.Windows.Documents.IDocumentPaginatorSource` object (eg `System.Windows.Documents.FixedDocument`, `System.Windows.Documents.FixedDocumentSequence`, `System.Windows.Documents.FlowDocument`, ...).

The library's objective is to supply you with a printing API, not with an XpsDocument-factory (which is _your_ task) 😌

**Comment by KutanaDev** [comment]
Many thanks. I opened an XpsDocument and then called GetFixedDocumentSequence and cast the return value to a IDocumentPaginatorSource, like this:

    XpsDocument xd = new XpsDocument(@"t:\work\Case4823\Input.xps", System.IO.FileAccess.Read);
    FixedDocumentSequence fds = xd.GetFixedDocumentSequence();
    IDocumentPaginatorSource documentPaginatorSource = fds as IDocumentPaginatorSource;

And this works fine. I'm glad this agrees with your suggestion!

**Comment by dittodhole** [comment]
As a final note: You don't have to explicitly cast a `System.Windows.Documents.FixedDocumentSequence` object to `System.Windows.Documents.IDocumentPaginatorSource`, as the CLR will do that cast implicitly for you :clap:
