### ISSUE TITLE
Paper trays are reported even when they're not installed

### ISSUE THREAD

**Issue by KutanaDev** [dittodhole/dotnet-Contrib.System.Printing.Xps#2]
[Kyocera.Reported.PaperTrays.txt](https://github.com/dittodhole/dotnet-Contrib.System.Printing.Xps/files/2262551/Kyocera.Reported.PaperTrays.txt)
I use the supplied sample code to enumerate the installed Paper Trays for the Kyocera TASKalfa 5551xi printer, and it lists all the trays that could possibly be installed, not just the ones that actually are installed. These are listed in the attached Kyocera.Reported.PaperTrays.txt, which dumps the PrintTicket xml for each reported tray.
 
The attached PrintCapabilities xml document for that printer has the paper trays marked with a **constrained** attribute. Trays with the attribute **constrained="psk:None"** are ticked as installed in the driver UI. Trays that have the attribute **constrained="psk:DeviceSettings"** are unticked in the driver UI, indicating they are not installed. 

But the enumeration lists the trays irrespective of the valued of the **constrained** attribute.

[PrintCapabilities.Kyocera TASKalfa 5551ci KX.xml.txt](https://github.com/dittodhole/dotnet-Contrib.System.Printing.Xps/files/2262520/PrintCapabilities.Kyocera.TASKalfa.5551ci.KX.xml.txt)

**Comment by dittodhole** [comment]
Thanks for sheding some light on the `constrained`-attribute :+1:

There are multiple possible solutions:
* Ignore the unticked input bins (changes behaviour of the library)
* Add the `active`-state to `IXpsInputBinDefinition` and let the client do the filtering (needs to be implemented in the library)
* Add the `active`-state to a derivate of `IXpsInputBinDefinition` and let the client do the filtering (can be implemented in a custom derivate of `IXpsServer`)

Anyway, feel free to implement a fix and provide a PR, which I will happily integrate.

**Comment by dittodhole** [comment]
I have added a way to query for available input bins only in the latest _develop_ branch, which is available via myget (see https://github.com/dittodhole/dotnet-Contrib.System.Printing.Xps#mygetorg):

* `GetAvailableXpsInputBinDefinitions`: Returns available input bins only (based on `GetXpsInputBinDefinitions`)
* `GetXpsInputBinDefinitions`: Remains untouched, as I don't want to break existing usages. Anyway, a client can do the filtering afterwards with the `IsAvailable`-property.

Please test this fix, as I do not have any printer available to do the testing 😢

**Comment by dittodhole** [comment]
I am assuming this issue has been fixed, as no response was given within one year.

If this issue still remains, feel free to reply!
