### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by KutanaDev** [dittodhole/dotnet-Contrib.System.Printing.Xps#3]
I know that if I implement the **WritingPrintTicketRequired** delegate method for the **XpsDocumentWriter** class then when I call the class **Write** method my delegate will be called multiple times giving me the chance to supply a PrintTicket for the job (FixedDocumentSequence) and for each FixedDocument in the FDS, and for each FixedPage in each FD.

The supplied **IXpsPrinterDefinition.Print** method is implemented using **XpsDocumentWriter** but it doesn't use the delegate method so there's no way of switching paper trays. So the only PrintTicket that has any effect is the one supplied on the Write call.  I'd really like to be able to specify different paper trays for p1 and subsequent pages in the FixedDocuments in my xps file. Would it be possible to create an extension method that did the delegate handling allowing tray switching at the page level?

**Comment by dittodhole** [comment]
Sorry, this question is beyond my scope of implementation (which I needed).
You have to implement a workaround yourself - PR welcome!

**Comment by dittodhole** [comment]
Just an idea: You could split the pages according to trays and use the existing interface.
